/*
 * $ Copyright 2016-YEAR Cypress Semiconductor $
 */
/**
 * All common definitions for this SPAR
 */
#pragma once

/* ACL config */
#ifndef APP_CFG_BT_ACL_HOST_TO_DEVICE_COUNT
#define APP_CFG_BT_ACL_HOST_TO_DEVICE_COUNT         8 //BT_ACL_HOST_TO_DEVICE_DEFAULT_COUNT
#endif
#ifndef APP_CFG_BT_ACL_DEVICE_TO_HOST_COUNT
#define APP_CFG_BT_ACL_DEVICE_TO_HOST_COUNT         12 //BT_ACL_DEVICE_TO_HOST_DEFAULT_COUNT
#endif

/* LE ACL config */
// ((BT_BLE_HOST_CLAIM_HOST_TO_DEVICE_DEFAULT_SIZE + BLE_ACL_BUF_SIZE_OVERHEAD) & ~0x3) + (((BT_BLE_HOST_CLAIM_HOST_TO_DEVICE_DEFAULT_SIZE + BLE_ACL_BUF_SIZE_OVERHEAD) & 0x3)?4:0)
#define APP_BT_BLE_HOST_TO_DEVICE_DEFAULT_SIZE      264
//((BT_BLE_DEVICE_CLAIM_DEVICE_TO_HOST_DEFAULT_SIZE + BLE_ACL_BUF_SIZE_OVERHEAD) & ~0x3) + (((BT_BLE_DEVICE_CLAIM_DEVICE_TO_HOST_DEFAULT_SIZE + BLE_ACL_BUF_SIZE_OVERHEAD) & 0x3)?4:0)
#define APP_BT_BLE_DEVICE_TO_HOST_DEFAULT_SIZE      264

#ifndef APP_CFG_BT_BLE_HOST_TO_DEVICE_COUNT
#define APP_CFG_BT_BLE_HOST_TO_DEVICE_COUNT         16 //BT_BLE_HOST_TO_DEVICE_DEFAULT_COUNT
#endif
#ifndef APP_CFG_BT_BLE_DEVICE_TO_HOST_COUNT
#define APP_CFG_BT_BLE_DEVICE_TO_HOST_COUNT         16 //BT_BLE_DEVICE_TO_HOST_DEFAULT_COUNT
#endif

/* Dynamic memory config */
#ifndef APP_CFG_DYNMEM_SIZE_1
#define APP_CFG_DYNMEM_SIZE_1                       DEFAULT_DYNMEM_SIZE_1
#endif
#ifndef APP_CFG_DYNMEM_COUNT_1
#define APP_CFG_DYNMEM_COUNT_1                      DEFAULT_DYNMEM_COUNT_1
#endif
#ifndef APP_CFG_DYNMEM_DIE_RESERVE_1
#define APP_CFG_DYNMEM_DIE_RESERVE_1                DEFAULT_DYNMEM_DIE_RESERVE_1
#endif
#ifndef APP_CFG_DYNMEM_SIZE_2
#define APP_CFG_DYNMEM_SIZE_2                       DEFAULT_DYNMEM_SIZE_2
#endif
#ifndef APP_CFG_DYNMEM_COUNT_2
#define APP_CFG_DYNMEM_COUNT_2                      DEFAULT_DYNMEM_COUNT_2
#endif
#ifndef APP_CFG_DYNMEM_DIE_RESERVE_2
#define APP_CFG_DYNMEM_DIE_RESERVE_2                DEFAULT_DYNMEM_DIE_RESERVE_2
#endif
#ifndef APP_CFG_DYNMEM_SIZE_3
#define APP_CFG_DYNMEM_SIZE_3                       DEFAULT_DYNMEM_SIZE_3
#endif
#ifndef APP_CFG_DYNMEM_COUNT_3
#define APP_CFG_DYNMEM_COUNT_3                      DEFAULT_DYNMEM_COUNT_3
#endif
#ifndef APP_CFG_DYNMEM_DIE_RESERVE_3
#define APP_CFG_DYNMEM_DIE_RESERVE_3                DEFAULT_DYNMEM_DIE_RESERVE_3
#endif
#ifndef APP_CFG_DYNMEM_SIZE_4
#define APP_CFG_DYNMEM_SIZE_4                       DEFAULT_DYNMEM_SIZE_4
#endif
#ifndef APP_CFG_DYNMEM_COUNT_4
#define APP_CFG_DYNMEM_COUNT_4                      8 //DEFAULT_DYNMEM_COUNT_4
#endif
#ifndef APP_CFG_DYNMEM_DIE_RESERVE_4
#define APP_CFG_DYNMEM_DIE_RESERVE_4                DEFAULT_DYNMEM_DIE_RESERVE_4
#endif


/* ble_con_max */
#ifndef APP_CFG_ULP_MAX_CONNECTION
#define APP_CFG_ULP_MAX_CONNECTION                  4 //ULP_MAX_CONNECTION
#endif

/* LE ISO buffer */
#ifndef APP_CFG_BT_BLE_ISOC_HOST_TO_DEVICE_COUNT
#define APP_CFG_BT_BLE_ISOC_HOST_TO_DEVICE_COUNT    1 //BT_BLE_ISOC_HOST_TO_DEVICE_DEFAULT_COUNT
#endif
#ifndef APP_CFG_BT_BLE_ISOC_DEVICE_TO_HOST_COUNT
#define APP_CFG_BT_BLE_ISOC_DEVICE_TO_HOST_COUNT    1 //BT_BLE_ISOC_DEVICE_TO_HOST_DEFAULT_COUNT
#endif
#ifndef APP_CFG_BT_BLE_ISOC_DEVICE_TX_PDU_COUNT
#define APP_CFG_BT_BLE_ISOC_DEVICE_TX_PDU_COUNT     1 //BT_BLE_ISOC_DEVICE_TX_PDU_DEFAULT_COUNT
#endif
#ifndef APP_CFG_BT_BLE_ISOC_DEVICE_RX_PDU_COUNT
#define APP_CFG_BT_BLE_ISOC_DEVICE_RX_PDU_COUNT     1 //BT_BLE_ISOC_DEVICE_RX_PDU_DEFAULT_COUNT
#endif
#ifndef APP_CFG_BT_BLE_ISOC_DEVICE_PDU_RB_ELEMENT_COUNT
#define APP_CFG_BT_BLE_ISOC_DEVICE_PDU_RB_ELEMENT_COUNT     1 //BT_BLE_ISOC_DEVICE_PDU_RB_ELEMENT_COUNT
#endif

/* Audio Enable */
#ifndef APP_CFG_ENABLE_BR_AUDIO
#define APP_CFG_ENABLE_BR_AUDIO                     0
#endif
#ifndef APP_CFG_BR_AUDIO_CFG
#define APP_CFG_BR_AUDIO_CFG                        NULL
#endif

/*  Enable Maximum Frequency 192 MHz Support for H1 CP */
#if defined(APP_CFG_ENABLE_MAX_SYS_FREQ_192MHz) && (APP_CFG_ENABLE_MAX_SYS_FREQ_192MHz == 1)
#define APP_CFG_MAX_FREQ_EN                          1
#else
#define APP_CFG_MAX_FREQ_EN                          0
#endif

/*  LPO Source Selection */
#define APP_CFG_LPO_SOURCE_SELECTION_TARGET_DEFAULT  0x0
#define APP_CFG_LPO_SOURCE_SELECTION_ILPO1           0x1
#define APP_CFG_LPO_SOURCE_SELECTION_ILPO2           0x2
#define APP_CFG_LPO_SOURCE_SELECTION_LHL_XTAL_IN     0x3
#define APP_CFG_LPO_SOURCE_SELECTION_ELPO_IN         0x4

#if defined(APP_CFG_LPO_SOURCE_SELECTION) && \
    ((APP_CFG_LPO_SOURCE_SELECTION > APP_CFG_LPO_SOURCE_SELECTION_TARGET_DEFAULT) && \
     (APP_CFG_LPO_SOURCE_SELECTION <= APP_CFG_LPO_SOURCE_SELECTION_ELPO_IN))
#define APP_CFG_LPO_SRC_SEL                          APP_CFG_LPO_SOURCE_SELECTION
#else
#define APP_CFG_LPO_SRC_SEL                          APP_CFG_LPO_SOURCE_SELECTION_TARGET_DEFAULT
#endif

#define APP_CFG_LPO_SRC_SEL_654_MAX_FREQ_EN_0        ((APP_CFG_LPO_SRC_SEL << 4) | APP_CFG_MAX_FREQ_EN)
